### ISSUE TITLE
favicon问题请教

### ISSUE THREAD

**Issue by carpediemvv** [swiftdo/web-demo#2]
favicon.png 在web里替换了，浏览器标签还是一直显示flutter的favicon.
这个您看有思路解决吗

**Comment by OHeroJ** [comment]
你的做法是对的，直接 web 目录下替换就可以，我这边没做处理。

如果没生效，建议清理下 build 目录。

以下是我替换后的效果：

<img width="744" alt="image" src="https://user-images.githubusercontent.com/12316547/178095146-d086d8eb-33bb-4683-a080-a4f8f0eb9c52.png">
